Gallery
aswanip-git/figma-landing-page pull request #5
Opened 2022-07-20 15:21 UTC by aswanip-git

2022-07-20 16:55 UTC, abanseka approved these changes

2022-07-21 09:01 UTC, kumbu132 requested changes

2022-07-21 09:01 UTC, kumbu132 commented on src/components/Contents/Contents.js
> +        <p className="contentsTitle">Contents</p>
use `kebab-case` for classnames unless you're using CSS modules.

2022-07-26 07:36 UTC, abanseka approved these changes

2022-07-26 07:40 UTC, merged